---
- name: Install nginx and PHP 7.4 packages
  apt:
    pkg:
      - nginx
      - unzip
      - php-imagick
      - php7.4-zip
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
    update_cache: true

- name: Setting up nginx vhost config
  template:
    src: vhost.nginx.conf.j2
    dest: /etc/nginx/conf.d/blog.conf

- name: Remove /etc/nginx/sites-enabled/default file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Install certbot
  pip:
    name:
      - certbot
      - certbot-nginx
    executable: pip3
  tags:
    - nginx
    - certbot

- name: Register certbot
  shell: |
    certbot -n register --agree-tos --email oi@raphaeldevs.com.br
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered
  tags:
    - nginx
    - certbot

- name: Setup cronjob for renewal
  cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
    minute: "0"
    hour: "14"
  tags:
    - nginx
    - certbot

- name: "Get certificate"
  command: "/usr/local/bin/certbot -n --nginx certonly -d {{ hostname }}"
  args:
    creates: "/etc/letsencrypt/live/{{ hostname }}"
  ignore_errors: true
  tags:
    - nginx
    - certbot

- name: Download Wordpress project and unzip
  unarchive:
    src: https://wordpress.org/latest.zip
    dest: /var/www/html
    remote_src: true

- name: Rename Wordpress folder to blog
  command:
    cmd: mv /var/www/html/wordpress /var/www/html/blog

- name: Updating wp-config
  template:
    src: wp-config.php.j2
    dest: /var/www/html/blog/wp-config.php

- name: Change Wordpress folder owner (permissions)
  file:
    path: /var/www/html/blog
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
